from __future__ import annotations

import re

from collections import defaultdict
from typing import Dict

from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.Chem.rdMolDescriptors import CalcMolFormula


# Monoisotopic atomic masses.
MONOISOTOPIC_MASSES: Dict[str, float] = {
    "H": 1.00782503223,
    "C": 12.0,
    "N": 14.00307400443,
    "O": 15.99491461957,
    "F": 18.99840316273,
    "P": 30.97376199842,
    "S": 31.9720711744,
    "Cl": 34.968852682,
    "Br": 78.9183376,
    "I": 126.904468,
    "Si": 27.97692653465,
    "B": 11.00930536,
}


def smiles_to_mol(
    smiles: str,
) -> Chem.Mol:
    """
    Parse SMILES into an RDKit molecule.

    Raises
    ------
    ValueError
        If RDKit cannot parse the SMILES.
    """

    mol = Chem.MolFromSmiles(smiles)

    if mol is None:
        raise ValueError(
            f"Invalid SMILES: {smiles}"
        )

    return mol


def canonicalize_smiles(
    smiles: str,
) -> str:
    """
    Return canonical RDKit SMILES.
    """

    mol = smiles_to_mol(smiles)

    return Chem.MolToSmiles(
        mol,
        canonical=True,
    )


def exact_mass_from_smiles(
    smiles: str,
) -> float:
    """
    Return RDKit exact monoisotopic mass.
    """

    mol = smiles_to_mol(smiles)

    return float(
        Descriptors.ExactMolWt(mol)
    )


def formula_from_smiles(
    smiles: str,
) -> str:
    """
    Return molecular formula generated by RDKit.
    """

    mol = smiles_to_mol(smiles)

    return CalcMolFormula(mol)


def parse_formula(
    formula: str,
) -> Dict[str, int]:
    """
    Parse a molecular formula into elemental counts.

    Supported examples:

        C6H12O6
        C20H15N3O2
        C10H12ClNO
        C12H19N2O2+
        C8H10N4O2-

    Terminal charge annotations are ignored when calculating
    elemental composition.

    Notes
    -----
    This function parses elemental composition only.
    Charge itself is not included in the returned dictionary.
    """

    if not formula:
        raise ValueError(
            "Formula cannot be empty."
        )

    formula = formula.strip()

    # Remove a terminal charge annotation such as:
    #
    # C12H19N2O2+
    # C8H10N4O2-
    # C10H20N2+2
    # C10H20N2-2
    #
    # The elemental composition remains unchanged.
    formula = re.sub(
        r"[+-]\d*$",
        "",
        formula,
    )

    if not formula:
        raise ValueError(
            "Formula contains no elemental composition."
        )

    counts: Dict[str, int] = defaultdict(int)

    i = 0

    while i < len(formula):

        if not formula[i].isupper():
            raise ValueError(
                f"Invalid molecular formula: {formula}"
            )

        symbol = formula[i]
        i += 1

        if (
            i < len(formula)
            and formula[i].islower()
        ):
            symbol += formula[i]
            i += 1

        digits = ""

        while (
            i < len(formula)
            and formula[i].isdigit()
        ):
            digits += formula[i]
            i += 1

        count = (
            int(digits)
            if digits
            else 1
        )

        counts[symbol] += count

    return dict(counts)


def exact_mass_from_formula(
    formula: str,
) -> float:
    """
    Calculate monoisotopic neutral mass from molecular formula.
    """

    composition = parse_formula(formula)

    total_mass = 0.0

    for element, count in composition.items():

        if element not in MONOISOTOPIC_MASSES:
            raise KeyError(
                f"Unsupported element "
                f"'{element}' in formula "
                f"'{formula}'."
            )

        total_mass += (
            MONOISOTOPIC_MASSES[element]
            * count
        )

    return total_mass


def formula_matches_smiles(
    smiles: str,
    expected_formula: str,
) -> bool:
    """
    Check whether the RDKit formula of a SMILES exactly matches
    an expected molecular formula.
    """

    calculated_formula = (
        formula_from_smiles(smiles)
    )

    return (
        calculated_formula
        == expected_formula
    )